### ISSUE TITLE
jigdo-X - all Debian packages

### ISSUE THREAD

**Issue by TCB13** [slowpeek/debian-iso-guide#1]
Hello,

I was exploring this repository and testing a bit with jigdo and I noticed something that might not be entire correct. 

> [jigdo-X](https://github.com/slowpeek/debian-iso-guide#jigdo-x)
Here you can see some files with .jigdo and .template extensions. With that you can reconstruct all iso images not readily available to download.
> Complete sets of DVD, BD and DLBD iso images contain the same set of debs, namely all Debian packages. The single 16G image is severely cut down compared to other variants.

In theory those images should contain all Debian packages, however when I download them they seem to be about 90GB when the official mirror for the same architecture lists 500GB.

Considering this: https://cdimage.debian.org/debian-cd/12.1.0/amd64/jigdo-bd/

![image](https://github.com/slowpeek/debian-iso-guide/assets/6315832/d869d38b-9c44-4d3e-a707-1bf622cbaf92)

````
$ du -sch debian-12.1.0-amd64-BD-*.iso
23G     debian-12.1.0-amd64-BD-1.iso
23G     debian-12.1.0-amd64-BD-2.iso
23G     debian-12.1.0-amd64-BD-3.iso
22G     debian-12.1.0-amd64-BD-4.iso
89G     total
````

Do you have any ideia about why this might be happening?

Thank you.

**Comment by slowpeek** [comment]
I guess those 655 gb include debian stable, oldstable, oldoldstable, testing and sid packages. There is likely something more there. Just look into some [mirror](http://ftp.de.debian.org/debian/dists/). The bd images you've downloaded only contain the stable stuff.

**Comment by TCB13** [comment]
Oh that makes perfect sense!
